{{- if .Values.serviceAccounts.sparkoperator.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-operator.serviceAccountName" . }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-failed
  labels:
    {{- include "spark-operator.labels" . | nindent 4 }}
{{- end }}
