name: Pre-commit checks

on:
  pull_request:
    branches:
      - master

  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: fmt check
        run: make fmt-check

      - name: unit tests
        run: make test

  it:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1

      - name: Print ct version information and List files
        run: ct version && ls -lh

      - name: Run chart-testing (lint)
        run: ct lint

      - name: Detect CRDs drift between chart and manifest
        run: make detect-crds-drift

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0

      - name: Run chart-testing (install)
        run: ct install
